# Generated by Django 5.2.6 on 2025-10-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='un-branded', max_length=250),
        ),
    ]
