# Generated by Django 5.2.6 on 2025-11-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_dimensions_product_discountpercentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
