# Generated by Django 5.2.6 on 2026-01-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_reserved_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountpercentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='折扣百分比', max_digits=5),
        ),
    ]
