# Generated by Django 5.2.6 on 2026-01-22 03:57

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_discountpercentage'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RemoveIndex(
            model_name='product',
            name='store_produ_categor_ca64c7_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_fake', 'price'], name='store_produ_categor_4e2eb0_idx'),
        ),
    ]
