# Generated by Django 5.2.6 on 2026-01-22 04:06

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_store_produ_categor_ca64c7_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='product_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['brand'], name='product_brand_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
