# Generated by Django 5.2.6 on 2025-10-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='orfer',
            new_name='order',
        ),
    ]
