# Generated by Django 5.2.6 on 2025-11-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_order_shipped_at_order_shipping_carruer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_carruer',
            new_name='shipping_carrier',
        ),
    ]
