# Generated by Django 5.2.6 on 2025-11-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_rename_shipping_carruer_order_shipping_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_capture_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verify_webhook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
