# Generated by Django 5.2.6 on 2026-01-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('order', '訂單問題'), ('refund', '付款問題'), ('product', '商品提問'), ('account', '帳號問題'), ('OTHER', '其他')], default='OTHER', max_length=20),
        ),
    ]
