# Generated by Django 5.2.6 on 2025-11-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkStockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '批次匯入庫存',
                'verbose_name_plural': '批次匯入庫存',
                'managed': False,
            },
        ),
    ]
