# Generated by Django 5.2.6 on 2025-11-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_bulkstockentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkstockentry',
            options={'managed': False, 'verbose_name': 'Bulk Stock Manager', 'verbose_name_plural': 'Bulk Stock Manager'},
        ),
    ]
