# Generated by Django 5.2.6 on 2025-11-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_google_user',
            field=models.BooleanField(default=False),
        ),
    ]
